name: DevSpace CLI Install
author: loft.sh
description: Installs the devspace CLI
inputs:
  version:
    description: 'The version of devspace to install'
    required: false
    default: 'latest'
  kubectl-install:
    description: 'Install kubectl if not already installed'
    required: false
    default: 'false'
  kubectl-version:
    description: 'The version of the kubectl to install'
    required: false
    default: 'latest'
runs:
  using: 'node20'
  main: 'dist/index.js'
